package com.javasm.mybatis.bean;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depts.dept_id
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    private Integer deptId;

    @Override
    public String toString() {
        return "Dept{" +
                "deptId=" + deptId +
                ", deptName='" + deptName + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_depts.dept_name
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depts.dept_id
     *
     * @return the value of tb_depts.dept_id
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depts.dept_id
     *
     * @param deptId the value for tb_depts.dept_id
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_depts.dept_name
     *
     * @return the value of tb_depts.dept_name
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_depts.dept_name
     *
     * @param deptName the value for tb_depts.dept_name
     *
     * @mbggenerated Wed May 04 23:52:55 CST 2022
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}