package com.javasm.mybatis.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.emp_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private Integer empId;

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", deptId=" + deptId +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.emp_name
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.age
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.gender
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.email
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employees.dept_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.emp_id
     *
     * @return the value of tb_employees.emp_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.emp_id
     *
     * @param empId the value for tb_employees.emp_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.emp_name
     *
     * @return the value of tb_employees.emp_name
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.emp_name
     *
     * @param empName the value for tb_employees.emp_name
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.age
     *
     * @return the value of tb_employees.age
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.age
     *
     * @param age the value for tb_employees.age
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.gender
     *
     * @return the value of tb_employees.gender
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.gender
     *
     * @param gender the value for tb_employees.gender
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.email
     *
     * @return the value of tb_employees.email
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.email
     *
     * @param email the value for tb_employees.email
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employees.dept_id
     *
     * @return the value of tb_employees.dept_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employees.dept_id
     *
     * @param deptId the value for tb_employees.dept_id
     *
     * @mbggenerated Wed May 04 23:52:54 CST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}